// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwP2Af9f9PYUi225uhDQj48sgNhI5jkI',
    appId: '1:594351917684:web:27e988875f05c3cd499f21',
    messagingSenderId: '594351917684',
    projectId: 'places-notes-app',
    authDomain: 'places-notes-app.firebaseapp.com',
    storageBucket: 'places-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJBdejceBefSWe5AmT8-h4GkqUG1b6yA',
    appId: '1:594351917684:android:8d0336b92aa9705f499f21',
    messagingSenderId: '594351917684',
    projectId: 'places-notes-app',
    storageBucket: 'places-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_CrVtPJr1NqgP7aPyfjTonBZRm9n1GA',
    appId: '1:594351917684:ios:783ff0d3bf68db35499f21',
    messagingSenderId: '594351917684',
    projectId: 'places-notes-app',
    storageBucket: 'places-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.placesNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_CrVtPJr1NqgP7aPyfjTonBZRm9n1GA',
    appId: '1:594351917684:ios:783ff0d3bf68db35499f21',
    messagingSenderId: '594351917684',
    projectId: 'places-notes-app',
    storageBucket: 'places-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.placesNotesApp',
  );
}
